services:
  catalogdb:
   image: postgres
   
  eshopmicro.catalogapi:
    image: ${DOCKER_REGISTRY-}eshopmicrocatalogapi
    build:
      context: ..
      dockerfile: src/Catalog/EshopMicro.CatalogApi/Dockerfile

volumes:
  postgres_catalog:

