services:
  catalogdb:
   image: postgres
  basketdb:
   image: postgres

  distributedcache:
    image: redis
    ports:
      - "6379:6379"
  orderdb:
    image: mcr.microsoft.com/mssql/server

  catalogapi:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: ..
      dockerfile: src/Catalog/CatalogApi/Dockerfile

  basket.api:
    image: ${DOCKER_REGISTRY-}basketapi
    build:
      context: .
      dockerfile: Basket/Basket.API/Dockerfile

  discount.grpc:
    image: ${DOCKER_REGISTRY-}discountgrpc
    build:
      context: .
      dockerfile: Discount/Discount.Grpc/Dockerfile

volumes:
  postgres_catalog:
  postgres_basket:
  sqlvolume:
