services:
  catalogdb:
   image: postgres
  basketdb:
   image: postgres

  distributedcache:
    image: redis
    ports:
      - "6379:6379"

  catalogapi:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: ..
      dockerfile: src/Catalog/CatalogApi/Dockerfile

volumes:
  postgres_catalog:
  postgres_basket:


